### PR TITLE
Drop pins on blas and curl

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
There is no need to pin `curl` unless we can't use the conda-forge pinned version:
https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/cf7013c1cb21a2c650ae0e51cc59e4ec519da935/recipe/conda_build_config.yaml#L370-L371

I have followed the preferred way of pinning blas is described under: https://conda-forge.org/docs/maintainer/knowledge_base.html#blas

**Comment by xylar** [comment]
These changes are needed because the pinned version of blas is different for architectures for which support was added recently.  But I wanted to make this change separately from #43 to avoid unnecessary confusion.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender.

**Comment by xylar** [comment]
@doutriaux1 and @dnadeau4, @muryanto1 has asked me to remove her as a maintainer from CDAT feedstocks.  Do you want me to do the same for you or do you prefer to keep an eye on things?

**Review by jasonb5 — APPROVED** [review]
LGTM

**Comment by xylar** [comment]
Thanks a lot @jasonb5 for giving this a look.

**Pull request merged**
