### PR TITLE
Fix build string to include python version

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@muryanto1, I'm going to hold off on merging this fix until I get a better understanding of whether we can just build with `nompi` versions and run with any MPI variant or if that is unsafe.

**Comment by muryanto1** [comment]
@xylar ok. thanks!

**Comment by xylar** [comment]
Replacing this with #37

**Pull request closed without merging**
