### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by doutriaux1**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dnadeau4** [comment]
@doutriaux1  I think I remember what the issue is with nccf_solve_double.  The config.h.in is not render properly and does not have the FC macros enable. 

https://github.com/CDAT/libcf/blob/master/cf_config.h#L24-L27

**Comment by doutriaux1** [comment]
We forgot to copy/paste the LD_SHARED flag. I think it will pass now.

**Comment by doutriaux1** [comment]
@dnadeau4 https://github.com/CDAT/libcf/blob/master/cf_config.h.in#L21-L24 has undef and the .h has a def. Do you think it is the issue? Should the recipe run autocnf?

**Comment by dnadeau4** [comment]
Yes this is the issue for `nccf_solve_double`.  Your ".in" is not configured properly.  I think master has a `config.h` that supersede the `config.h.in` created from `configure`.  If you look at `master` I recreated `configure.ac` and `configure` with `automake` and `aclocal`.

**Comment by doutriaux1** [comment]
Ok so which one do we want in the end? Do we want the .in to be processed and replace the .h or the otherway around we do NOT want the .in to overwrite the .h

**Comment by dnadeau4** [comment]
https://github.com/CDAT/libcf/commit/04f5fd4d2a69fedb81e96709fe04c0ed9e4f76d1#diff-67e997bcfdac55191033d57a16d1408a

I added new detection for lgfortran (configure.ac at the bottom)

**Comment by dnadeau4** [comment]
We want to trigger this.
https://github.com/CDAT/libcf/blob/master/configure.ac#L280-L302

**Comment by dnadeau4** [comment]
Yes it defined `FC_FUNC` with an underscore.

https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Fortran-Compiler.html
 Look under
```
 — Macro: AC_FC_WRAPPERS
```

**Pull request closed without merging**
