### PR TITLE
Switch from ossuuid to libuuid

### LINKED ISSUE #20: Conflict between ossuuid and libuuid
This library brings in `ossuuid`, which conflicts with `libuuid`:

```
ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::libuuid-2.32.1-h14c3975_1000, conda-forge::ossuuid-1.6.2-hf484d3e_1000
  path: 'lib/libuuid.a'


ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::libuuid-2.32.1-h14c3975_1000, conda-forge::ossuuid-1.6.2-hf484d3e_1000
  path: 'lib/libuuid.la'


ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::libuuid-2.32.1-h14c3975_1000, conda-forge::ossuuid-1.6.2-hf484d3e_1000
  path: 'lib/libuuid.so'


ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::libuuid-2.32.1-h14c3975_1000, conda-forge::ossuuid-1.6.2-hf484d3e_1000
  path: 'lib/pkgconfig/uuid.pc'
```

Would it be possible to build against `libuuid` instead?

See https://github.com/E3SM-Project/e3sm-unified/pull/39

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

closes #20

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@doutriaux1 or @dnadeau4, if you're okay with this change and me being added as a maintainer, please merge at your convenience.  I'm hoping to get a new version of E3SM-Unified done this week, and this would help.

**Comment by doutriaux1** [comment]
@xylar I will bring these changes back into nightly and make sure it doesn't break any of our test suites.

**Comment by xylar** [comment]
Okay, that sounds good.  If it does, I think the solution would still be to convert to `libuuid` and try to figure out how to fix things downstream.  It's problematic for `conda-forge` users if this package conflicts with others.

**Comment by doutriaux1** [comment]
@xylar agreed, but if things break it will slow down the process ;)

**Comment by xylar** [comment]
Yep, that's understandable.

**Comment by dnadeau4** [comment]
@xylar I don't see any change in the code.  I would be surprise that`ossuuid` will give the same result as `libuuid`.   I don't think it has the same API either.

**Comment by xylar** [comment]
If that's the case, the recipe for `ossuuid` should be made to produce a library with a different name from `libuuid` so they don't conflict.  Otherwise, one overwrites the other when a user creates an environment with both.

**Comment by dnadeau4** [comment]
@xylar you are right.  We used `ossuuid`, but I don't know who owns it.  It is no longer maintan so we should use `libuuid` and tell our user that the CMIP6 tracker_id as a different format.  I on think it is only use by computer database, nobody is parsing it manually.  I need to ask ESGF about how the publisher use the `tracking_id`

**Comment by xylar** [comment]
Okay, great!  I think I can mostly work around this issue by forcing a reinstall of `libuuid` for now but I would prefer not to have the conflict at all.  Please keep me posted on what you find.

**Comment by xylar** [comment]
@doutriaux1, any luck with this change in your nightly testing?

**Comment by doutriaux1** [comment]
Nah it fails, Denis took it over.

C.

**Comment by xylar** [comment]
Okay, thanks for the update.  Keep me posted and let me know if there's anything I can do to help.

**Comment by dnadeau4** [comment]
I got things to work on Mac, but now it fails on Linux.  I will go into circleci this afternoon.

**Comment by xylar** [comment]
Any headway on this?  I know you're both busy.  I just want to give some context for why I'm pushing on this.  I've been trying for months to get a release of the E3SM unified metapackage together, and it's been a real challenge this time.  I'm nearly there but this is one of a few remaining issues preventing me from a release.

**Comment by dnadeau4** [comment]
I will look at it today, but CMOR will also need to change to `libuuid`.

**Comment by xylar** [comment]
Okay, I actually think I'm just going to live with the conflicts for now and hope for the best.  It seems a little troubling but I do need to move along and clearly this conflict has gone unnoticed for quite awhile without any obvious side effects at least in our workflow.

@dnadeau4 and @doutriaux1, I'd recommend you both try building with the `path_conflict: prevent` set in your `.condarc` just so you notice these conflicts as they come up.

**Comment by dnadeau4** [comment]
@xylar  I was able to compile libcf and use it to generate a `uuid`.
```python
>>> from ctypes import *
>>> import numpy
>>> libcf = CDLL('/software/anaconda53/envs/cdms2/lib/libcf.so')
>>> bt=numpy.ones(80,dtype='<U18')
>>> buffer=bt.ctypes.data_as(c_char_p)
>>> libcf.nccf_generate_id(9,buffer)
>>> buffer.value
b'fe51c283-b406-445e-b321-61562228b7d2'
```

I will merge your PR

**Comment by dnadeau4** [comment]
@conda-forge-admin, please rerender

**Comment by dnadeau4** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
