### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by muryanto1**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by muryanto1** [comment]
@conda-forge-admin, please rerender

**Comment by doutriaux1** [comment]
@muryanto1 it llooks like you pushed directly to conda-forge this is actually pretty bad... if it fails on one platfrom we will have builds for one but not the other available and we will have to start incrementing the build numbers... It's ok though, just conda-forge folks do not like direct pushes.

**Comment by dnadeau4** [comment]
We did not push to conda-forge, we used muryanto1 fork

**Comment by doutriaux1** [comment]
my bad! It comes from your repo! Please accept my apologies and forget my rant!

**Comment by doutriaux1** [comment]
@dnadeau4 thank you so much for this!

**Pull request merged**
