### PR TITLE
Update pins

### PR DESCRIPTION
**Pull request by ocefpaf**
See conda-forge/conda-forge.github.io#482

### CODE REVIEW

**Comment by doutriaux1** [comment]
@ocefpaf I'm worried we have many other libraries using hdf5, will they find the older build unitl they all get re-pinned?

**Comment by doutriaux1** [comment]
@ocefpaf what about netcdf? Are you guys moving to 4.5 ?

**Comment by doutriaux1** [comment]
@dnadeau4 any comments on this? I missed the original ping from @ocefpaf a week ago.

**Comment by ocefpaf** [comment]
> @ocefpaf I'm worried we have many other libraries using hdf5, will they find the older build unitl they all get re-pinned?

Yep. Everything is getting pinned to `hdf5 1.10.1`. If you find errors due to that please ping me so we can fix it ASAP.

> what about netcdf? Are you guys moving to 4.5 ?

Unfortunately not yet. `libnetcdf 4.5.0` does not build with `vc 9`. That means we cannot use it to build Windows extensions for Python 2.7. So we are probably going to hang on `libnetcdf 4.4` for a while.

**Comment by dnadeau4** [comment]
I saw the libcf one but not this one.  This will break ESMF for OSX.  As well, CMOR that I just released last week won't work in the same environment of your next release.

**Comment by ocefpaf** [comment]
> This will break ESMF for OSX

Can you elaborate on that? Are conda-forge's `esmf` should work with this pinning scheme. I don't know if conda-forge has CMOR packaged though.

**Comment by dnadeau4** [comment]
You don't have `ESMF `for `OSX` and Python 3 yet. It is in development in another channel and we link with it for our python 3 version of `CDMS2`.  [nesii/channel/dev-esmf](https://anaconda.org/NESII/esmf/files)

`CMOR` is not part of conda-forge, but we compile it with all conda-forge libraries and it comes with `cdms2`.  It is distributed from the PCMDI channel. We add CDMS2 to conda-forge with all the depencies, but not all our packages are in the conda-forge channel.   I released version `3.2.8` last week.
https://anaconda.org/PCMDI/cmor/files

```
package:
    name: cmor
    version: 3.2.8

source:
    git_rev: master
    git_url: git://github.com/PCMDI/cmor.git

build:
  number: 0

test:
  requires:
    - python
    - libgcc [osx]
  imports:
    - cmor

requirements:
  build:
    - python 
    - ossuuid 1.6.2.*
    - udunits2
    - hdf5 1.8.18|1.8.18.*
    - libnetcdf 4.4.*
    - numpy {{ NPY_VER }}
    - libgcc [osx]
  run:
    - python
    - ossuuid 1.6.2.*
    - udunits2
    - hdf5 1.8.18|1.8.18.*
    - libnetcdf 4.4.*
    - numpy {{ NPY_VER }}
    - cdms2
    - libgcc [osx]

about:
    home:  http://github.com/PCMDI
```

**Comment by ocefpaf** [comment]
> You don't have `ESMF `for `OSX` and Python 3 yet. It is in development in another channel and we link with it for our python 3 version of `CDMS2`.  [nesii/channel/dev-esmf](https://anaconda.org/NESII/esmf/files)

It is kind of ironic that we need a dev version of something but an old version of another :smile: 

Adding the development version of `esmf` is in my to do list for conda-forge, but I don't think I'll be able to get to it soon. If you want to try let me know and I can help with the PR.

> `CMOR` is not part of conda-forge, but we compile it with all conda-forge libraries and it comes with `cdms2`.  It is distributed from the PCMDI channel. We add CDMS2 to conda-forge with all the depencies, but not all our packages are in the conda-forge channel.   I released version `3.2.8` last week.

Do you want to release it in conda-forge? Ping me and I can help you with that.

PS: the pinning update here should not hurt your environment though. Conda should install the previous build number for `libcf`, however, that can fail if some of the dependencies were not properly pinned at some point making that behavior unreliable.

**Comment by dnadeau4** [comment]
@taylor13 @durack1 @gleckler1  Would you like to see CMOR released in the conda-forge channel?

@ocefpaf thanks hopefully conda will behave. 😄

**Pull request merged**
