### PR TITLE
Rerender

### LINKED ISSUE #2: osx not build
Somehow, master had requirement `toochain` instead of `toolchain`  I fixed it and  push to master, but `travis` was not triggered.  I noticed there is no `.travis.yaml` in the directory.  Can some take a look at my directory? 

thanks!

### PR DESCRIPTION
**Pull request by ocefpaf**
Closes #2 and #1 

@dnadeau4 all I did was to get your changes from #1 and rerender.

### CODE REVIEW

**Comment by dnadeau4** [comment]
I did rerender but did not take [osx] out of the toolchain meta.yaml.  
Thanks!

**Comment by ocefpaf** [comment]
That  should not make a difference though. I'll check it later. If this
passes feel free to merge it.

**Comment by dnadeau4** [comment]
Ok thanks again.

**Comment by ocefpaf** [comment]
> Ok thanks again.

No problem.

**Pull request merged**
